### ISSUE TITLE
GridPatternView - View with few elements will be scrollable when it shouldn't

### ISSUE THREAD

**Issue by greatergoodguy** [EmirWeb/parchment#1]
I created a simple GridPatternView that copies the setup from the demo activity. I used my own adapter and populated the View with very minimal items. I notice some strange scrolling when this happens. 

This image shows what the layout looks like upon entering the Activity. The expectations is that this view should not scroll.

However, the view will scroll until the item is anchored to the bottom.

![2014-04-17 20 56 54](https://cloud.githubusercontent.com/assets/965103/2736866/fe20db28-c672-11e3-8693-d20394cfced5.png)

![2014-04-17 20 57 15](https://cloud.githubusercontent.com/assets/965103/2736872/1017ec90-c673-11e3-9a93-a696f99daabe.png)
![2014-04-17 20 57 00](https://cloud.githubusercontent.com/assets/965103/2736875/1853753c-c673-11e3-93d8-d53e797ef654.png)

**Comment by emir-hasanbegovic** [comment]
The fix is in master as of 1.6.7
