### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by coanag** [EmirWeb/parchment#16]
Hi Emir,
thank you for that library.
I tested the sample app you provided in this git and it very good.
Im having trouble setting it up in my project in Android studio.
I get also Error:Attribute "orientation" has already been defined
Should i download picasso library too?
Should i import other files from your library?

Thank you in advance

**Comment by emir-hasanbegovic** [comment]
The best way to run the sample app is to open it in android studio, and to open it by double clicking the pom.xml file. That should do it. If you have never used maven and Android Studio before, there will be a steep learning curve, but one gotcha. In project settings/structure, under modules, under dependencies. you need to change the module sdk to "Android SDK XX" as opposed to "Maven Android SDK XX"
