### ISSUE TITLE
GridPatternView - App will crash unless user defines a GridPatternItemDefinitions

### ISSUE THREAD

**Issue by greatergoodguy** [EmirWeb/parchment#2]
When using the GridPatternView, it seems that the user is required to set a GridPatternItemDefinition, otherwise the app will crash. I think it'd be better for the user is there is no crash and it is not required of the user to set up a GridPatternItemDefinition to get the app to run.

Looking at the logs, it seems that the crash is caused by a divide by zero error in the function "getCellPosition()" in the class "GridPatternLayoutManager". Perhaps we can guard against this at the library level.

04-17 17:34:13.667: E/AndroidRuntime(26304): java.lang.ArithmeticException: divide by zero
04-17 17:34:13.667: E/AndroidRuntime(26304):    at mobi.parchment.widget.adapterview.gridpatternview.GridPatternLayoutManager.getCellPosition(GridPatternLayoutManager.java:381)
04-17 17:34:13.667: E/AndroidRuntime(26304):    at mobi.parchment.widget.adapterview.gridpatternview.GridPatternLayoutManager.getCellCount(GridPatternLayoutManager.java:376)
04-17 17:34:13.667: E/AndroidRuntime(26304):    at mobi.parchment.widget.adapterview.LayoutManager.incrementCellPosition(LayoutManager.java:646)
04-17 17:34:13.667: E/AndroidRuntime(26304):    at mobi.parchment.widget.adapterview.LayoutManager.layoutCells(LayoutManager.java:579)
04-17 17:34:13.667: E/AndroidRuntime(26304):    at mobi.parchment.widget.adapterview.LayoutManager.layout(LayoutManager.java:195)

**Comment by emir-hasanbegovic** [comment]
I've added the bug here, https://www.pivotaltracker.com/story/show/70282066 if you want to follow the progress

**Comment by emir-hasanbegovic** [comment]
A fix has been started in the CenterOnScreen branch. Still working out a few small bugs, please keep updated

**Comment by emir-hasanbegovic** [comment]
Master has the changes
