### ISSUE TITLE
GridPatternView - isCircularScroll does not seem to work

### ISSUE THREAD

**Issue by greatergoodguy** [EmirWeb/parchment#6]
My expectations is that 'isCircularScroll' is a toggle between cyclical scrolling and scrolling with a top and bottom bound. The current behavior is always cyclical scrolling regardless of what the 'isCircularScroll' attribute is set to.

**Comment by greatergoodguy** [comment]
My mistake. Issue is non-existent.

**Comment by broakenmedia** [comment]
How did you fix this?
